version: "3.8"
services:
  postgres:
    image: postgres:15-alpine3.17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_mooi_studio
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
    ports:
      - 5432:5432
  server:
    build:
      context: ./server
      dockerfile: docker/dev.dockerfile
    working_dir: /mooi-studio
    ports:
      - 4001:4001
    volumes:
      - ./server:/mooi-studio
    environment:
      APP_ENV: DEVELOPMENT
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
